
name : push

on :
  push :
    branches : [ master ]

jobs :

  Full :
    if : "startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest ]
        node-version : [ 10.x, 12.x, 13.x, 14.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
    - run : wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/docker-compose.yml
    - run : wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/mailserver.env
    - run : wget -O .env https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/ed7106b04d545be6320a6943bd4a367e8622c8d6/compose.env
    - run : docker-compose up -d mailserver
    - run : docker exec mail addmailuser user@domain.com password
    - run : docker-compose restart
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - name : npm test
      run : npm test
      env :
        WTOOLS_BOT_TOKEN : ${{ secrets.WTOOLS_BOT_TOKEN }}

  Fast :
    if : "!startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest ]
        node-version : [ 14.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
    - run : wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/docker-compose.yml
    - run : wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/mailserver.env
    - run : wget -O .env https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/ed7106b04d545be6320a6943bd4a367e8622c8d6/compose.env
    - run : docker-compose up -d mailserver
    - run : docker exec mail addmailuser user@domain.com password
    - run : docker-compose restart
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - name : npm test
      run : npm test
      env :
        WTOOLS_BOT_TOKEN : ${{ secrets.WTOOLS_BOT_TOKEN }}

